# Generated by Django 5.0.1 on 2024-02-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_code_sent_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="последняя отправка кода"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_code",
            field=models.CharField(
                blank=True,
                max_length=4,
                null=True,
                verbose_name="одноразовый код подтверждения",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="имя"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="активен"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="фамилия"
            ),
        ),
    ]
