# Generated by Django 5.0.1 on 2024-02-14 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_invite_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="invited_users",
            field=models.ManyToManyField(
                related_name="приглашенные пользователи", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
