# Generated by Django 5.0.1 on 2024-02-14 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_invited_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="invited_users",
        ),
        migrations.AddField(
            model_name="user",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invited_users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пригласил",
            ),
        ),
    ]
